# Generated by Django 5.2.4 on 2025-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotel_address_hotel_contact_number_hotel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
