# Generated by Django 5.2.4 on 2025-07-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hotel_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_type',
        ),
    ]
