# Generated by Django 5.2.4 on 2025-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_hotel_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowmore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='knowmore/')),
            ],
            options={
                'db_table': 'KNOWMORE',
            },
        ),
    ]
