# Generated by Django 5.2.4 on 2025-07-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_knowmore'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowMoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='knowmore/')),
            ],
            options={
                'db_table': 'knowmore_image',
            },
        ),
        migrations.CreateModel(
            name='KnowMoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'knowmore_section',
            },
        ),
        migrations.DeleteModel(
            name='Knowmore',
        ),
        migrations.AddField(
            model_name='knowmoreimage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.knowmoresection'),
        ),
    ]
