# Generated by Django 5.2.4 on 2025-07-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_knowmoreimage_knowmoresection_delete_knowmore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowmore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='knowmore/')),
            ],
            options={
                'db_table': 'KNOWMORE',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.hotel')),
            ],
            options={
                'db_table': 'HOTEL_IMAGES',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(help_text='E.g., 32 m² / 344 ft²', max_length=50)),
                ('bed_type', models.CharField(help_text='E.g., 1 queen bed', max_length=50)),
                ('view', models.CharField(blank=True, help_text='E.g., Garden view', max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.hotel')),
            ],
            options={
                'db_table': 'ROOMS',
            },
        ),
        migrations.DeleteModel(
            name='KnowMoreImage',
        ),
        migrations.DeleteModel(
            name='KnowMoreSection',
        ),
    ]
