# Generated by Django 5.2.4 on 2025-07-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_knowmore_hotelimage_room_delete_knowmoreimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
