# Generated by Django 5.2.4 on 2025-07-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_room_hotel_delete_hotelimage_delete_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knowmore',
        ),
    ]
