# Generated by Django 5.2.4 on 2025-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_knowmore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'CONTACTMESSAGE',
            },
        ),
    ]
