# Generated by Django 5.2.4 on 2025-08-03 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlights', models.TextField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('map_embed_url', models.URLField(blank=True, null=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.hotel')),
            ],
            options={
                'db_table': 'HOTELDETAIL',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_gallery/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.hotel')),
            ],
            options={
                'db_table': 'HOTELIMAGE',
            },
        ),
    ]
