# Generated by Django 5.2.4 on 2025-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_hoteldetail_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetail',
            name='cleanliness_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='facilities_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='location_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='review_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='service_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='total_reviews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
