# Generated by Django 5.2.4 on 2025-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hoteldetail_cleanliness_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetail',
            name='map_embed_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='hoteldetail',
            table=None,
        ),
    ]
