# Generated by Django 5.2.4 on 2025-08-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_hoteldetail_map_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('child_ages_csv', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(default='India', max_length=60)),
                ('pref_smoking', models.CharField(blank=True, choices=[('non', 'Non‑smoking'), ('smoking', 'Smoking')], max_length=12)),
                ('pref_bed', models.CharField(blank=True, choices=[('large', 'Large bed'), ('twin', 'Twin beds')], max_length=12)),
                ('extra_requests', models.TextField(blank=True)),
                ('computed_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.hotel')),
            ],
        ),
    ]
