# Generated by Django 5.2.4 on 2025-08-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='image',
            new_name='main_image',
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.package')),
            ],
        ),
    ]
