# Generated by Django 5.2.4 on 2025-08-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_image_package_main_image_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='region',
            field=models.CharField(choices=[('north', 'North Andaman'), ('south', 'South Andaman'), ('middle', 'Middle Andaman'), ('little', 'Little Andaman')], default='south', max_length=20),
        ),
    ]
