# Generated by Django 5.2.4 on 2025-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_packageday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageday',
            options={'ordering': ['day_number']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='guide_gender',
        ),
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='main_image',
            field=models.ImageField(upload_to='package/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='package/gallery/'),
        ),
    ]
