# Generated by Django 5.2.4 on 2025-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_packageday_options_remove_package_guide_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accommodation_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='package',
            name='customer_reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='map_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='transfers_meals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
