# Generated by Django 5.2.4 on 2025-08-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_package_accommodation_info_package_avg_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
