# Generated by Django 5.2.4 on 2025-08-31 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_chatplace'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatplace',
            table='chatplace',
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('child_ages_csv', models.CharField(blank=True, default='', max_length=100)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Arrival')], default='upi', max_length=20)),
                ('computed_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to='main.package')),
            ],
        ),
    ]
