# Generated by Django 5.2.4 on 2025-08-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_chatplace_table_packagebooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatplace',
            options={'managed': False},
        ),
    ]
