# Generated by Django 5.2.4 on 2025-08-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_chatplace_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagebooking',
            table='packagebooking',
        ),
    ]
